/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a06ex01;

import javax.swing.ImageIcon;

/**
 *
 * @author ALUNO
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private int pontosUser = 0;
    private int pontosPC = 0;
    private String pauseGame = "";

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        btnNovoJogo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPedraPC = new javax.swing.JLabel();
        lblPapelPC = new javax.swing.JLabel();
        lblTesouraPC = new javax.swing.JLabel();
        lblPedra = new javax.swing.JLabel();
        lblPapel = new javax.swing.JLabel();
        lblTesoura = new javax.swing.JLabel();
        lblPontos = new javax.swing.JLabel();
        lblPontosPC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNovoJogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pedra, Papel e Tesoura");
        setResizable(false);

        lblPedraPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pedra.png"))); // NOI18N
        lblPedraPC.setEnabled(false);

        lblPapelPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/papel.png"))); // NOI18N
        lblPapelPC.setEnabled(false);

        lblTesouraPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tesoura.png"))); // NOI18N
        lblTesouraPC.setEnabled(false);

        lblPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pedra.png"))); // NOI18N
        lblPedra.setToolTipText("pedra");
        lblPedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPedraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPedraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPedraMouseExited(evt);
            }
        });

        lblPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/papel.png"))); // NOI18N
        lblPapel.setToolTipText("papel");
        lblPapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPapelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPapelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPapelMouseExited(evt);
            }
        });

        lblTesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tesoura.png"))); // NOI18N
        lblTesoura.setToolTipText("tesoura");
        lblTesoura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTesouraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTesouraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTesouraMouseExited(evt);
            }
        });

        lblPontos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPontos.setText("000");

        lblPontosPC.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPontosPC.setText("000");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("X");

        btnNovoJogo.setText("Novo Jogo");
        btnNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoJogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(lblPontos))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPedra)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnNovoJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPapel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(27, 27, 27)
                            .addComponent(lblTesoura)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPedraPC)
                            .addGap(18, 18, 18)
                            .addComponent(lblPapelPC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(lblTesouraPC))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(138, 138, 138)
                            .addComponent(lblPontosPC))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(158, 158, 158)
                            .addComponent(jLabel1))))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblPontosPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPapelPC, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPedraPC)
                    .addComponent(lblTesouraPC))
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovoJogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPapel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTesoura, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPedra, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPontos)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblPedraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedraMouseEntered
        if(pauseGame.equals(""))
            lblPedra.setIcon(new ImageIcon(getClass().getResource("/icons/pedra_azul.png")));
    }//GEN-LAST:event_lblPedraMouseEntered

    private void lblPedraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedraMouseExited
        if(pauseGame.equals(""))
            lblPedra.setIcon(new ImageIcon(getClass().getResource("/icons/pedra.png")));
    }//GEN-LAST:event_lblPedraMouseExited

    private void lblPapelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPapelMouseEntered
        if(pauseGame.equals(""))
            lblPapel.setIcon(new ImageIcon(getClass().getResource("/icons/papel_azul.png")));
    }//GEN-LAST:event_lblPapelMouseEntered

    private void lblPapelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPapelMouseExited
        if(pauseGame.equals(""))
            lblPapel.setIcon(new ImageIcon(getClass().getResource("/icons/papel.png")));
    }//GEN-LAST:event_lblPapelMouseExited

    private void lblTesouraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTesouraMouseEntered
        if(pauseGame.equals(""))
            lblTesoura.setIcon(new ImageIcon(getClass().getResource("/icons/tesoura_azul.png")));
    }//GEN-LAST:event_lblTesouraMouseEntered

    private void lblTesouraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTesouraMouseExited
        if(pauseGame.equals(""))
            lblTesoura.setIcon(new ImageIcon(getClass().getResource("/icons/tesoura.png")));
    }//GEN-LAST:event_lblTesouraMouseExited

    private void lblPedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedraMouseClicked
        lblPapel.setEnabled(false);
        lblTesoura.setEnabled(false);
        this.realizaJogada(lblPedra);
    }//GEN-LAST:event_lblPedraMouseClicked

    private void lblPapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPapelMouseClicked
        lblPedra.setEnabled(false);
        lblTesoura.setEnabled(false);
        this.realizaJogada(lblPapel);
    }//GEN-LAST:event_lblPapelMouseClicked

    private void lblTesouraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTesouraMouseClicked
        lblPedra.setEnabled(false);
        lblPapel.setEnabled(false);
        this.realizaJogada(lblTesoura);
    }//GEN-LAST:event_lblTesouraMouseClicked

    private void btnNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoJogoActionPerformed
        this.pauseGame = "";
        btnNovoJogo.setVisible(false);
        
        lblPedraPC.setEnabled(false);
        lblPapelPC.setEnabled(false);
        lblTesouraPC.setEnabled(false);
        
        lblPedra.setIcon(new ImageIcon(getClass().getResource("/icons/pedra.png")));
        lblPapel.setIcon(new ImageIcon(getClass().getResource("/icons/papel.png")));
        lblTesoura.setIcon(new ImageIcon(getClass().getResource("/icons/tesoura.png")));
        lblPedra.setEnabled(true);
        lblPapel.setEnabled(true);
        lblTesoura.setEnabled(true);
    }//GEN-LAST:event_btnNovoJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    private void realizaJogada(javax.swing.JLabel label) {
        if(btnNovoJogo.isVisible())
            return;
        
        String jogadaPC = this.jogadaPC();
        String vitoria = this.verificaVitoria(label.getToolTipText(), jogadaPC);
        this.pauseGame = "pause";        
        
        // Modifica os botões após as jogadas
        if(vitoria.equals("user")) {
            lblPontos.setText(++pontosUser + "");
            this.defineBotoesUser(label, jogadaPC);
        } else if(vitoria.equals("pc")) {
            lblPontosPC.setText(++pontosPC + "");
            this.defineBotoesPC(label, jogadaPC);
        } else {   
            this.defineBotoesEmpate(label, jogadaPC);
        }
        
        btnNovoJogo.setVisible(true);
    }
    
    private void defineBotoesUser(javax.swing.JLabel label, String jogadaPC) {
        label.setIcon(new ImageIcon(getClass().getResource("/icons/" + label.getToolTipText() + "_win.gif")));

        if(jogadaPC.equals("pedra")) lblPedraPC.setEnabled(true);
        if(jogadaPC.equals("papel")) lblPapelPC.setEnabled(true);
        if(jogadaPC.equals("tesoura")) lblTesouraPC.setEnabled(true);
    }
    
    private void defineBotoesPC(javax.swing.JLabel label, String jogadaPC) {
        label.setIcon(new ImageIcon(getClass().getResource("/icons/" + label.getToolTipText() + "_azul.png")));

        if(jogadaPC.equals("pedra")) lblPedraPC.setEnabled(true);
        if(jogadaPC.equals("papel")) lblPapelPC.setEnabled(true);
        if(jogadaPC.equals("tesoura")) lblTesouraPC.setEnabled(true);
    }

    private void defineBotoesEmpate(javax.swing.JLabel label, String jogadaPC) {
        label.setIcon(new ImageIcon(getClass().getResource("/icons/" + label.getToolTipText() + ".png")));

        if(jogadaPC.equals("pedra")) lblPedraPC.setEnabled(true);
        if(jogadaPC.equals("papel")) lblPapelPC.setEnabled(true);
        if(jogadaPC.equals("tesoura")) lblTesouraPC.setEnabled(true);
    }
    
    private String jogadaPC() {
        int randomPCInt = (int) (Math.random() * 3);
        String jogadaPC = "";
        
        switch(randomPCInt) {
            case 0 -> {
                lblPedraPC.setEnabled(true);
                jogadaPC = "pedra";
            }
            case 1 -> {
                lblPapelPC.setEnabled(true);
                jogadaPC = "papel";
            }
            case 2 -> {
                lblTesouraPC.setEnabled(true);
                jogadaPC = "tesoura";
            }
        }
        
        return jogadaPC;
    }
    
    private String verificaVitoria(String jogadaUser, String jogadaPC) {
        String vitoria;
        
        if( (jogadaUser.equals("pedra") && jogadaPC.equals("tesoura")) || 
            (jogadaUser.equals("papel") && jogadaPC.equals("pedra"))   || 
            (jogadaUser.equals("tesoura") && jogadaPC.equals("papel"))
        ) {
            vitoria = "user";
        } else if (
            (jogadaUser.equals("pedra") && jogadaPC.equals("papel"))   ||
            (jogadaUser.equals("papel") && jogadaPC.equals("tesoura")) ||
            (jogadaUser.equals("tesoura") && jogadaPC.equals("pedra"))
        ) {
            vitoria = "pc";
        } else {
            vitoria = "empate";
        }
        
        return vitoria;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoJogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPapel;
    private javax.swing.JLabel lblPapelPC;
    private javax.swing.JLabel lblPedra;
    private javax.swing.JLabel lblPedraPC;
    private javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lblPontosPC;
    private javax.swing.JLabel lblTesoura;
    private javax.swing.JLabel lblTesouraPC;
    // End of variables declaration//GEN-END:variables
}
