/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package todososjogos;

/**
 *
 * @author ALUNO
 */
public class JogoSoma2 extends javax.swing.JFrame {

    // definindo variaveis globais
    private int acertos = 0;
    private int erros = 0;
    private String status = "";
    private int numero1 = 0;
    private int numero2 = 0;
    
    /**
     * Creates new form JogoSoma2
     */
    public JogoSoma2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAcertos = new javax.swing.JLabel();
        lblErros = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        lblNumero2 = new javax.swing.JLabel();
        lblNumero1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnResposta1 = new javax.swing.JButton();
        btnResposta2 = new javax.swing.JButton();
        btnResposta3 = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pontuação:");

        lblAcertos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAcertos.setForeground(new java.awt.Color(0, 0, 255));
        lblAcertos.setText("000");

        lblErros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblErros.setForeground(new java.awt.Color(255, 0, 0));
        lblErros.setText("000");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        lblNumero2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblNumero2.setText("0");

        lblNumero1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblNumero1.setText("0");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("+");

        btnResposta1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnResposta1.setText("0");
        btnResposta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResposta1ActionPerformed(evt);
            }
        });

        btnResposta2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnResposta2.setText("0");
        btnResposta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResposta2ActionPerformed(evt);
            }
        });

        btnResposta3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnResposta3.setText("0");
        btnResposta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResposta3ActionPerformed(evt);
            }
        });

        lblStatus.setText("Status: escolha a resposta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(lblNumero1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(14, 14, 14)
                                .addComponent(lblNumero2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lblStatus)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAcertos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblErros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNovo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResposta2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResposta3, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblAcertos)
                        .addComponent(lblErros))
                    .addComponent(btnNovo))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumero2)
                        .addComponent(lblNumero1)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResposta2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResposta3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        randomizeNumbers();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnResposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResposta1ActionPerformed
        if(Integer.valueOf(btnResposta1.getText()) == (numero1 + numero2)){
            acertos++;
            status = "Você acertou!";
        } else {
            erros++;
            status = "Você errou!";
        }
        
        lblStatus.setText(status);
        lblAcertos.setText("" + acertos);
        lblErros.setText("" + erros);
        
        randomizeNumbers();
    }//GEN-LAST:event_btnResposta1ActionPerformed

    private void btnResposta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResposta2ActionPerformed
        if(Integer.valueOf(btnResposta2.getText()) == (numero1 + numero2)){
            acertos++;
            status = "Você acertou!";
        } else {
            erros++;
            status = "Você errou!";
        }
        
        lblStatus.setText(status);
        lblAcertos.setText("" + acertos);
        lblErros.setText("" + erros);
        
        randomizeNumbers();
    }//GEN-LAST:event_btnResposta2ActionPerformed

    private void btnResposta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResposta3ActionPerformed
        if(Integer.valueOf(btnResposta3.getText()) == (numero1 + numero2)){
            acertos++;
            status = "Você acertou!";
        } else {
            erros++;
            status = "Você errou!";
        }
        
        lblStatus.setText(status);
        lblAcertos.setText("" + acertos);
        lblErros.setText("" + erros);
        
        randomizeNumbers();
    }//GEN-LAST:event_btnResposta3ActionPerformed

    private void randomizeNumbers() {
        numero1 = (int) (Math.random() * 10);
        numero2 = (int) (Math.random() * 10);
        lblNumero1.setText("" + numero1);
        lblNumero2.setText("" + numero2);
        
        btnResposta1.setText("" + ((int) (Math.random() * 10)));
        btnResposta2.setText("" + ((int) (Math.random() * 10)));
        btnResposta3.setText("" + ((int) (Math.random() * 10)));
        
        int sorteio = (int) (Math.random() * 10);
        
        if(sorteio <= 10 && sorteio >= 7) {
            btnResposta1.setText("" + (numero1 + numero2));
        } else if(sorteio <= 6 && sorteio >= 3) {
            btnResposta2.setText("" + (numero1 + numero2));
        } else {
            btnResposta3.setText("" + (numero1 + numero2));
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoSoma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoSoma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoSoma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoSoma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoSoma2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnResposta1;
    private javax.swing.JButton btnResposta2;
    private javax.swing.JButton btnResposta3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAcertos;
    private javax.swing.JLabel lblErros;
    private javax.swing.JLabel lblNumero1;
    private javax.swing.JLabel lblNumero2;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
